service: covid-19-data-etl-data-to-s3
app: covid-19-data-etl
org: timothygithinji
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::covid-19-data-etl-timothygithinji/data/*"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource: "arn:aws:sns:us-east-1:144272576793:covid-19-data-etl"

package:
  exclude:
    - venv/**

functions:
  hello:
    handler: handler.hello
    events:
      - eventBridge:
          schedule: cron(0 12 * * ? *)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux